# Overview of the Julia Language

## References:

- http://learnxinyminutes.com/docs/julia/
- http://dmbates.blogspot.com/2012/04/r-programmer-looks-at-julia.html
- http://www.r-bloggers.com/a-beginners-look-at-julia/
- https://github.com/JuliaLang/julia
- http://nbviewer.ipython.org/urls/raw.github.com/johnmyleswhite/DCStats.jl/master/Setup.ipynb
- http://julialang.org/blog/2012/03/shelling-out-sucks/
- http://docs.julialang.org/en/latest/manual/running-external-programs/
- http://julialang.org/blog/2013/04/put-this-in-your-pipe/
- http://julialang.org/blog/2013/09/fast-numeric/
- http://www.admin-magazine.com/HPC/Articles/Parallel-Julia-Jumping-Right-In
- http://web.mit.edu/julia_v1.24.13/www/index.html
- http://nbviewer.ipython.org/url/jdj.mit.edu/~stevenj/IJulia%2520Preview.ipynb
- http://strata.oreilly.com/2012/10/matlab-r-julia-languages-for-data-analysis.html
- http://asbidyarthy.blogspot.com/2012/06/julia-programming-language-downloads.html
- http://jurjenbokma.com/ApprenticesNotes/getting_statlinked_binaries_on_debian.html

## Preliminaries

- Quitting Julia: [ctrl]-D or quit()
- Abort or clear current command: [ctrl]-C
- Parentheses ( ) are used for functions and multiple outputs
- Brackets [ ] are used for indexing
- Braces { } are used for arrays
- Running a file: include("file.jl") or require("file.jl")
- Printing values: print() or println()
- Deployment: main.jl 
      #!/fullpath/julia
      
      arg=ARGS[1];
      println("Hello $arg");
      
  in shell: ./main.jl World => Hello World

#### External Shell Calls: 

In [1]:
run(`cal`)

   November 2015
Su Mo Tu We Th Fr Sa
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



#### C-Function Call:

In [2]:
ccall(:clock,Int32,())

5657538

In [3]:
bytestring(ccall(:ctime, Ptr{Uint8}, ()))

  likely near In[3]:1


"Sun Nov 20 19:46:08 2383\n"

#### Adding Package:

In [5]:
using Calendar

In [8]:
Calendar.hour(Calendar.now())

3

In [9]:
Calendar.dayofyear(Calendar.now())

318

## Variables, Vectors, and Matrices

In [9]:
x=3

3

In [10]:
x=[1,2,3] # column vector

3-element Array{Int64,1}:
 1
 2
 3

In [11]:
x[2]

2

In [12]:
x=[1 2 3 4] # row vector

1x4 Array{Int64,2}:
 1  2  3  4

In [13]:
x=(1,2,3,4)

(1,2,3,4)

In [14]:
x1,x2=1,2
println(x1,",",x2)

1,2


In [15]:
x1,x2=x2,x1 #swap x1,x2 values

(2,1)

In [16]:
x1

2

In [17]:
M=[1 2 3;4 5 6;7 8 9;10 11 12]  # matrix

4x3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [18]:
M=reshape(M,3,4)

3x4 Array{Int64,2}:
 1  10   8   6
 4   2  11   9
 7   5   3  12

In [19]:
M[1,:] # first row

1x4 Array{Int64,2}:
 1  10  8  6

In [20]:
M[:,1] # first column

3-element Array{Int64,1}:
 1
 4
 7

In [21]:
M[3,1:3] # 3rd row, first to third column

1x3 Array{Int64,2}:
 7  5  3

In [22]:
rand(5) # column vector of random numbers

5-element Array{Float64,1}:
 0.672032 
 0.0454474
 0.521723 
 0.432878 
 0.518976 

In [1]:
rand(5,5)::Array{Float64,1} # matrix of random numbers

LoadError: LoadError: TypeError: typeassert: expected Array{Float64,1}, got Array{Float64,2}
while loading In[1], in expression starting on line 1

In [24]:
eye(5)  # identity matrix

5x5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [25]:
a=zeros(5,5)

5x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [26]:
b=ones(5,5)

5x5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [27]:
linspace(1,2,10) 

10-element Array{Float64,1}:
 1.0    
 1.11111
 1.22222
 1.33333
 1.44444
 1.55556
 1.66667
 1.77778
 1.88889
 2.0    

In [28]:
A=diagm(ones(5))

5x5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [29]:
diag(A)

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [30]:
[sin(i) for i in 1:5] #comprehension

5-element Array{Float64,1}:
  0.841471
  0.909297
  0.14112 
 -0.756802
 -0.958924

In [31]:
map(sin,1:5)

5-element Array{Float64,1}:
  0.841471
  0.909297
  0.14112 
 -0.756802
 -0.958924

In [32]:
V=[(i,j) for i=1:3, j=4:10] 

3x7 Array{(Int64,Int64),2}:
 (1,4)  (1,5)  (1,6)  (1,7)  (1,8)  (1,9)  (1,10)
 (2,4)  (2,5)  (2,6)  (2,7)  (2,8)  (2,9)  (2,10)
 (3,4)  (3,5)  (3,6)  (3,7)  (3,8)  (3,9)  (3,10)

In [16]:
@time M=[sin(i+j) for i=1:100000,j=1:100];

elapsed time: 0.261267245 seconds (80000048 bytes allocated)


In [18]:
@time M = @parallel [sin(i+j) for i=1:1:100000,j=1:100];

elapsed time: 0.088676304 seconds (246596 bytes allocated)


In [3]:
addprocs(7)

7-element Array{Any,1}:
 2
 3
 4
 5
 6
 7
 8

## Function and Operations

In [19]:
a=3*8;
b=8/4;
c=4//8;
d=2^8;
println("$a,$b,$c,$d")

24,2.0,1//2,256


In [32]:
2^(2+3im)

-1.947977671863125 + 3.493620327099486im

In [33]:
sin(pi/3)

0.8660254037844386

In [34]:
besselj(2,5)

0.0465651162777522

In [35]:
f(x)=x*x

f (generic function with 1 method)

In [36]:
function f(x)
    x*x
end

f (generic function with 1 method)

In [37]:
f(3)

9

In [38]:
ff=function(x)
  x*x
end

(anonymous function)

In [40]:
p(sin(10))

-0.5440211108893698


In [ ]:
p=println
p(34)

In [ ]:
p=ff
p(4)

In [41]:
fff(x,y,z)=x*y*z

fff (generic function with 1 method)

In [42]:
fff(3,4,5)

60

In [46]:
map(x->x*x,[1,4,2])

3-element Array{Int64,1}:
  1
 16
  4

In [47]:
map(f,1:10)

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [ ]:
map(x->x*x,1:10)

In [48]:
map(1:10) do x
y=x*x
end

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [50]:
x=[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [51]:
3x

3-element Array{Int64,1}:
 3
 6
 9

In [52]:
x+3

3-element Array{Int64,1}:
 4
 5
 6

In [53]:
y=[2,4,6]

3-element Array{Int64,1}:
 2
 4
 6

In [54]:
x' * y   # dot product

1-element Array{Int64,1}:
 28

In [55]:
dot(x,y) # dot product

28

In [56]:
sum(conj(x).* y)  # dot product

28

In [57]:
x .* y  # elementwise multiplication

3-element Array{Int64,1}:
  2
  8
 18

In [ ]:
cos(x) 

In [58]:
A=rand(5,5)

5x5 Array{Float64,2}:
 0.927993  0.374016  0.509559  0.833871  0.412078
 0.461696  0.702475  0.929109  0.950646  0.158752
 0.762993  0.434505  0.864311  0.166177  0.658699
 0.514608  0.168586  0.924724  0.183062  0.358211
 0.661424  0.865718  0.139276  0.971936  0.445655

In [59]:
b=rand(5)

5-element Array{Float64,1}:
 0.367602 
 0.35236  
 0.0460402
 0.336241 
 0.419711 

In [61]:
x=A\b # solving for unknown x such that Ax=b

5-element Array{Float64,1}:
 -4.48121 
 -3.50258 
  0.383313
  3.73774 
  6.12515 

In [ ]:
x=pinv(A)*b # solving for unknown x such that Ax=b

In [62]:
A*x # Ax=b

5-element Array{Float64,1}:
 0.367602 
 0.35236  
 0.0460402
 0.336241 
 0.419711 

In [63]:
l,v=eig(A)

([2.85993957170964 + 0.0im,-0.07346264691893353 + 0.6642696139039639im,-0.07346264691893353 - 0.6642696139039639im,0.3758896842148505 + 0.0im,0.03459236984657424 + 0.0im],
5x5 Array{Complex{Float64},2}:
 0.463597+0.0im   0.063311+0.0930495im  …   0.727024+0.0im  -0.523379+0.0im
 0.484628+0.0im   0.0345079+0.517244im     -0.550211+0.0im  -0.326082+0.0im
 0.464942+0.0im   -0.143541-0.409397im     -0.147643+0.0im  0.0213109+0.0im
 0.342551+0.0im  -0.383221-0.0431418im      0.043814+0.0im   0.344278+0.0im
 0.465512+0.0im         0.617795+0.0im     -0.380771+0.0im   0.707646+0.0im)

In [64]:
methods(eig)

# 3 methods for generic function "eig":
eig(m::SymTridiagonal{T<:Union(Float32,Complex{Float64},Float64,Complex{Float32})}) at linalg/tridiag.jl:67
eig(A::AbstractArray{T,2},B::AbstractArray{T,2}) at linalg/factorization.jl:579
eig(A::Union(Number,AbstractArray{T,2})) at linalg/factorization.jl:502

# 16 methods for generic function "vcat":
vcat{T}(r::Range{T}) at range.jl:498
vcat() at abstractarray.jl:511
vcat{T}(rs::Range{T}...) at range.jl:511
vcat{T<:Number}(X::T<:Number...) at abstractarray.jl:518
vcat(X::Number...) at abstractarray.jl:521
vcat{T}(arrays::Array{T,1}...) at array.jl:993
vcat(V::BitArray{1}...) at bitarray.jl:1582
vcat(A::BitArray{2}...) at bitarray.jl:1620
vcat(X::SparseMatrixCSC{Tv,Ti<:Integer}...) at sparse/sparsematrix.jl:1639
vcat{T}(V::AbstractArray{T,1}...) at abstractarray.jl:545
vcat{T}(A::AbstractArray{T,2}...) at abstractarray.jl:594
vcat(A::AbstractArray{T,N}...) at abstractarray.jl:736
vcat{Tv<:Union(Complex{Float64},Float64,Complex{Float32},Float32)}(A::CholmodSparse{Tv<:Union(Complex{Float64},Float64,Complex{Float32},Float32),Int32},B::CholmodSparse{Tv<:Union(Complex{Float64},Float64,Complex{Float32},Float32),Int32}) at linalg/cholmod.jl:830
vcat{Tv<:Union(Complex{Float64},Float64,Complex{Float32},Float32)}(A::CholmodSparse{Tv<:Union(Complex{Float64},Float64,Complex{Float32},Float32),Int64},B::CholmodSparse{Tv<:Union(Complex{Float64},Float64,Complex{Float32},Float32),Int64}) at linalg/cholmod.jl:830
vcat{T}(X::T...) at abstractarray.jl:517
vcat(X...) at abstractarray.jl:670

In [65]:
v

5x5 Array{Complex{Float64},2}:
 0.463597+0.0im   0.063311+0.0930495im  …   0.727024+0.0im  -0.523379+0.0im
 0.484628+0.0im   0.0345079+0.517244im     -0.550211+0.0im  -0.326082+0.0im
 0.464942+0.0im   -0.143541-0.409397im     -0.147643+0.0im  0.0213109+0.0im
 0.342551+0.0im  -0.383221-0.0431418im      0.043814+0.0im   0.344278+0.0im
 0.465512+0.0im         0.617795+0.0im     -0.380771+0.0im   0.707646+0.0im

In [66]:
function f(x,y) 
  return(x+y,x-y)
end

f (generic function with 2 methods)

In [67]:
(res1,res2)=f(1,2)

(3,-1)

In [67]:
K=rand(2,2);
(u,d,v)=svd(K);

In [ ]:
K

In [ ]:
v

In [ ]:
u*diagm(d)*v'

In [ ]:
ndims(K)

In [ ]:
size(K)

In [ ]:
typeof(K)

In [23]:
x=randn(10);

In [33]:
[(i>0)?"+":"-" for i in x]'

1x10 Array{ASCIIString,2}:
 "+"  "-"  "-"  "-"  "+"  "+"  "+"  "+"  "-"  "+"

In [44]:
i=10;
if (i<10)
    print("hello")
else
    print("hi")
end

hi